spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ENDPOINT}:${PORT}/movie_project_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_ID}
    password: ${DB_PASSWORD}

  # redis setting
  redis:
    host: ${ENDPOINT}
    port: 6379
  session:
    store-type: redis

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mail:
  address:
    admin: admin@gmail.com

#https setting
server:
  servlet:
    session:
      timeout: 5m
      cookie:
        max-age: 5m
        http-only: true
  port: 8081