drop table if exists member CASCADE;
drop table if exists member_roles CASCADE;
create table member (
       id bigint generated by default as identity,
        created_at timestamp,
        updated_at timestamp,
        email varchar(255) not null,
        member_image varchar(255),
        password varchar(255) not null,
        warning_card integer not null,
        primary key (id)
);
create table member_roles (
       member_id bigint not null,
        roles varchar(255)
};